project:
  type: website
  output-dir: docs

website:
  title: "CCIEA Uploader"
  favicon: "figures/favicon.ico"
  search: false
  navbar:
    title: false
    background: "#276189"
    collapse: false
    search: false
    logo: "figures/logo-5.png"
    logo-alt: "California Current Integrated Ecosystem Assessment Website"
    logo-href: "https://www.integratedecosystemassessment.noaa.gov/regions/california-current"
    left:
    - text: "CCIEA Uploader"
      href: index.qmd
    - text: "How To"
      href: work_flow1.qmd
    - text: "FAQ"
      href: faq.qmd
    right:
    - text: "Status"
      href: status.qmd
    - icon: github
      href: https://github.com/CCIEA-esr/CCIEA-uploader

format:
  html:
    theme:
      - cosmo
      - custom.css
    grid:
      body-width: 1400px
      margin-width: 20px
      sidebar-width: 20px
resources:
  - data
  - figures




    